### ISSUE TITLE
Add execution time info to test output

### ISSUE THREAD

**Issue by marcingrzejszczak** [marcingrzejszczak/gradle-test-profiler#18]

**Comment by achudzik** [comment]
@marcingrzejszczak You want to do it only with --debug enabled? Is adding some additional param (specific to gradle-test-profiler) also acceptable?

**Comment by marcingrzejszczak** [comment]
Maybe adding it on -PtestProfiling property would be ok?

**Comment by marcingrzejszczak** [comment]
Done here - https://github.com/marcingrzejszczak/gradle-test-profiler/blob/master/src/main/groovy/com/blogspot/toomuchcoding/testprofiler/TestExecutionResultSavingTestListener.groovy#L33
