### ISSUE TITLE
Excel 2010 doesn't handle field separator in reports corretly

### ISSUE THREAD

**Issue by achudzik** [marcingrzejszczak/gradle-test-profiler#19]
Excel 2010 ignores the following field separators:
- comma - suggested in RFC4180
- tab - currently used as default in gradle-test-profiler

and use locale (and Windows) specific "list separator" property (e.g. semicolon).

See [this Stackoverflow question](https://stackoverflow.com/questions/838590/how-to-read-list-separator-from-os-in-java) for more details.

**Comment by mattfirtion** [comment]
I tried modifying the separator String in the testprofiler section, but the report will outputs tabs.

``` groovy
apply plugin: 'java'

buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.blogspot.toomuchcoding:gradle-test-profiler:0.3.1'
    }
}

apply plugin: 'com.blogspot.toomuchcoding.testprofiler'

repositories {
    mavenCentral()
}

dependencies {
    testCompile 'junit:junit:4.8.2'
}

testprofiler {  
    String separator = "|"
}
```

**Comment by marcingrzejszczak** [comment]
@achudzik - can you address this issue?

**Comment by marcingrzejszczak** [comment]
@mattfirtion - I'll try to take a look at this tomorrow. I'm really sorry for the delay.

**Comment by marcingrzejszczak** [comment]
@mattfirtion - you have written

```
testprofiler {  
    String separator = "|"
}
```

whereas you should

```
testprofiler {  
    separator = "|"
}
```

You have initialized a variable separator instead of setting it. Can you try like I just wrote and retry?

**Comment by mattfirtion** [comment]
@marcingrzejszczak, that worked.  I'd suggest changing README.md to match.  Any thought on changing the default from tabs to comma separated?

**Comment by marcingrzejszczak** [comment]
@mattfirtion - that would make perfect sense - I'll try to do that today. Is now readme better ? (https://github.com/marcingrzejszczak/gradle-test-profiler/commit/475307484c8b41fea7a25557671da5722fe4327c)

**Comment by mattfirtion** [comment]
Definitely!  I love the idea behind this plugin.

**Comment by marcingrzejszczak** [comment]
Enjoy :) https://bintray.com/marcingrzejszczak/com-blogspot-toomuchcoding/gradle-test-profiler/0.3.2/view 

Version 0.3.2 released with comma as default separation
