### ISSUE TITLE
Plugin logs report generated message even when profileTests task is not used

### ISSUE THREAD

**Issue by mattfirtion** [marcingrzejszczak/gradle-test-profiler#41]
Gradle will output that a test report is ready, even though profileTests task was not called.

**Comment by marcingrzejszczak** [comment]
Could you please show me your configuration of `build.gradle` ?

**Comment by mattfirtion** [comment]
``` groovy
apply plugin: 'java'

buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.blogspot.toomuchcoding:gradle-test-profiler:0.3.1'
    }
}

apply plugin: 'com.blogspot.toomuchcoding.testprofiler'

repositories {
    mavenCentral()
}

dependencies {
    testCompile 'junit:junit:4.8.2'
}

testprofiler {  
    String separator = "|"
}
```

Exec: gradle clean build

**Comment by marcingrzejszczak** [comment]
@achudzik - can you address this issue?

**Comment by marcingrzejszczak** [comment]
I think I know why ;)

By default reports are always created. The `profileTests` is combining the generated tests into one.

The default behaviour is such that test listener is automatically applied when you're applying the plugin. The test listener's behaviour results in creation of reports. You would have to disable the feature with the extension.

**Comment by marcingrzejszczak** [comment]
@mattfirtion - can we close it?

**Comment by marcingrzejszczak** [comment]
@mattfirtion  ping? :)

**Comment by marcingrzejszczak** [comment]
super ping? :P
