### ISSUE TITLE
csv report not generated for multi-project builds

### ISSUE THREAD

**Issue by mattfirtion** [marcingrzejszczak/gradle-test-profiler#42]
When applying the plugin to a subproject of a multi-project gradle project, the csv report is not created.

When running gradle with --info flag, the plugin is printing the contents of the csv, but the report is not in the destination directory.

Buildscript block was added to subproject's build.gradle

**Comment by marcingrzejszczak** [comment]
Could you provide a sample project? I'm asking about this cause I have successfully added this plugin to a couple of mulit-project gradle projects. I'm wondering how it differs.

**Comment by mattfirtion** [comment]
@marcingrzejszczak, please give me a day or so to put together a project.  The project in question is proprietary and I'll need to sanitize a bit.

**Comment by mattfirtion** [comment]
configuration issue on my end.
